title: Off The Rack
logo: "/assets/img/profile2.jpg"
description: 

  <p></p>

  A marketplace for young fashion entreprenuers. Our mission is to encourage to shop sustainably while supporting fashion entrepreneurs in our community.

google_analytics:
theme: jekyll-theme-minimal

